{% set name = "xforms" %}
{% set version = "0.9999.3" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
  url: http://software.igwn.org/sources/source/Xform-{{ version }}.tar.gz
  sha256: b2f0ffd29d1f8cea10c6c35749fd481acffd6e57a20db54d218caff69ea623a8

build:
  run_exports:
    - {{ pin_subpackage("xforms", max_pin="x") }}
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('expat') }}     # [linux]
    - meson >=0.50
    - ninja
    - pkg-config
    - jpeg
    - xorg-libx11
  host:
    - jpeg
    - xorg-libx11
    - xorg-libxfixes  # [linux]
  run:
    - jpeg
    - xorg-libx11
    - xorg-libxfixes  # [linux]

test:
  requires:
    - pkg-config
  commands:
    - test -x ${PREFIX}/bin/fdesign  # [unix]
    - test -f ${PREFIX}/lib/libforms.so  # [unix]
    - pkg-config --print-errors --modversion xforms
     

about:
  home: https://git.ligo.org/virgo/virgoapp/Xform/
  dev_url: https://git.ligo.org/virgo/virgoApp/Xform/
  license: "LGPL-2.0-only"
  license_family: "GPL"
  license_file: "COPYING"
  summary: XForms is a graphical user interface toolkit for X based on the X11 Xlib library
  description: |
           This is the first Open Source distribution of the XForms Library, a
           graphical user interface toolkit for X Window Systems.  It should be
           considered "provisional".  Hence the Version 0.9999.  There should be
           several more 9's following the decimal point.


extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn
