schema_version: 1

context:
  name: xforms
  version: 1.2.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://download.savannah.nongnu.org/releases/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 78cc6b07071bbeaa1f906e0a22d5e9980e48f8913577bc082d661afe5cb75696
  patches:
    - linker-error.patch

build:
  dynamic_linking:
    overdepending_behavior: error
    overlinking_behavior: error
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - autoconf
    - gnuconfig
    - make
  host:
    - if: linux
      then: libgl-devel
    - libjpeg-turbo
    - xorg-libx11
    - xorg-libxpm
    - xorg-xorgproto
  run_exports:
    - ${{ pin_subpackage("xforms", upper_bound="x") }}

tests:
  - package_contents:
      bin:
        - fdesign
        - fd2ps
      lib:
        - flimage
        - forms
        - if: linux
          then: formsGL
  - requirements:
      run:
        - pkg-config
    script:
      - fdesign -version
      - pkg-config --print-errors --exact-version "${{ version }}" xforms

about:
  summary: A GUI Toolkit for X Window Systems
  description: |
    Forms Library for X (xforms) is a GUI toolkit and builder for the
    X Window Systems and runs on all major UNIX platforms as well as OpenVMS and OS2.
    Forms Library is too complex to be described in the "man" page format.
    Ask your system administrator for the location of the HTML, PDF
    or PostScript document or follow the links on the Forms Library's home page
    for an online version of the documentation.
  homepage: http://xforms-toolkit.org/
  repository: https://cgit.git.savannah.nongnu.org/cgit/xforms.git
  license: LGPL-2.0-only
  license_file: COPYING.LIB

extra:
  recipe-maintainers:
    - duncanmmacleod
    - EmmanuelP
    - erinelizabethseder-virgo
    - fcarbogn
